export const isHiragana = (char: string) => /[\u3041-\u3096]/.test(char);
export const isKatakana = (char: string) => /[\u30a1-\u30f6]/.test(char);
export const isKana = (char: string) => isHiragana(char) || isKatakana(char);

export const isYoon = (source: string) => "きにひみりぎぢびぴ".includes(source[0]) && "ゃゅょ".includes(source[1]);
export const isSokuon = (source: string) => source[0] === "っ";
export const isHatuon = (source: string) => source[0] === "ん";

export const singleHiraganaToRomans: { [key: string]: string[] } = {
  あ: ["a"],
  い: ["i"],
  う: ["u"],
  え: ["e"],
  お: ["o"],
  か: ["ka"],
  き: ["ki"],
  く: ["ku"],
  け: ["ke"],
  こ: ["ko"],
  さ: ["sa"],
  し: ["si", "shi"],
  す: ["su"],
  せ: ["se"],
  そ: ["so"],
  た: ["ta"],
  ち: ["ti", "chi"],
  つ: ["tu", "tsu"],
  て: ["te"],
  と: ["to"],
  な: ["na"],
  に: ["ni"],
  ぬ: ["nu"],
  ね: ["ne"],
  の: ["no"],
  は: ["ha"],
  ひ: ["hi"],
  ふ: ["hu", "fu"],
  へ: ["he"],
  ほ: ["ho"],
  ま: ["ma"],
  み: ["mi"],
  む: ["mu"],
  め: ["me"],
  も: ["mo"],
  や: ["ya"],
  ゆ: ["yu"],
  よ: ["yo"],
  ら: ["ra"],
  り: ["ri"],
  る: ["ru"],
  れ: ["re"],
  ろ: ["ro"],
  わ: ["wa"],
  を: ["wo"],
  ん: ["nn"],
  ゔ: ["vu"],
  が: ["ga"],
  ぎ: ["gi"],
  ぐ: ["gu"],
  げ: ["ge"],
  ご: ["go"],
  ざ: ["za"],
  じ: ["zi", "ji"],
  ず: ["zu"],
  ぜ: ["ze"],
  ぞ: ["zo"],
  だ: ["da"],
  ぢ: ["di"],
  づ: ["du"],
  で: ["de"],
  ど: ["do"],
  ば: ["ba"],
  び: ["bi"],
  ぶ: ["bu"],
  べ: ["be"],
  ぼ: ["bo"],
  ぱ: ["pa"],
  ぴ: ["pi"],
  ぷ: ["pu"],
  ぺ: ["pe"],
  ぽ: ["po"],
  ぁ: ["xa", "la"],
  ぃ: ["xi", "li"],
  ぅ: ["xu", "lu"],
  ぇ: ["xe", "le"],
  ぉ: ["xo", "lo"],
  ゕ: ["xka", "lka"],
  ゖ: ["xke", "lke"],
  っ: ["xtu", "ltu", "xtsu", "ltsu"],
  ゃ: ["xya", "lya"],
  ゅ: ["xyu", "lyu"],
  ょ: ["xyo", "lyo"],
  ゎ: ["xwa", "lwa"]
};

export const pairHiraganaToRomans: { [key: string]: string[] | undefined } = {
  いぇ: ["ye"],
  うぃ: ["whi", "wi"],
  うぇ: ["whe", "we"],
  うぉ: ["who"],
  しゃ: ["sya", "sha"],
  しゅ: ["syu", "shu"],
  しょ: ["syo", "sho"],
  くぁ: ["kwa", "qa"],
  くぃ: ["kwi", "qi"],
  くぇ: ["kwe", "qe"],
  くぉ: ["kwo", "qo"],
  しぇ: ["sye", "she"],
  ちぇ: ["che"],
  ちゃ: ["tya", "cha"],
  ちゅ: ["tyu", "chu"],
  ちょ: ["tyo", "cho"],
  つぁ: ["tsa"],
  つぃ: ["tsi"],
  つぇ: ["tse"],
  つぉ: ["tso"],
  てぃ: ["thi"],
  てゅ: ["thu"],
  とぅ: ["twu"],
  とぉ: ["two"],
  ふぁ: ["fa", "hwa"],
  ふぃ: ["fi", "hwi"],
  ふぇ: ["fe", "hwe"],
  ふぉ: ["fo", "hwo"],
  ふゅ: ["fyu", "hwyu"],
  ゔぁ: ["va"],
  ゔぃ: ["vi"],
  ゔぇ: ["ve"],
  ゔぉ: ["vo"],
  ゔゅ: ["vyu"],
  ぐぁ: ["gwa"],
  ぐぃ: ["gwi"],
  ぐぇ: ["gwe"],
  ぐぉ: ["gwo"],
  じぇ: ["je", "zye"],
  じゃ: ["ja", "zya"],
  じゅ: ["ju", "zyu"],
  じょ: ["jo", "zyo"],
  ぢぇ: ["dye"],
  でぃ: ["dhi"],
  でゅ: ["dhu"],
  どぅ: ["dwu"],
  どぉ: ["dwo"]
};
