/**
 * This file was automatically generated by typescript-json-schema
 */
import { Definition } from "typescript-json-schema";

export const SaveParamsMapSchema: Definition = {
  type: "object",
  properties: {
    Exercise: {
      type: "object",
      properties: {
        title: { type: "string" },
        authorId: {
          format: "uuid",
          type: "string"
        },
        detailId: {
          format: "uuid",
          type: "string"
        },
        tagIds: {
          type: "array",
          items: { type: "string" }
        },
        lang: { type: "string" },
        description: { type: "string" },
        isPrivate: { type: "boolean" },
        isLocked: { type: "boolean" }
      }
    },
    ExerciseDetail: {
      type: "object",
      properties: {
        title: { type: "string" },
        lang: { type: "string" },
        description: { type: "string" },
        contentId: {
          format: "uuid",
          type: "string"
        },
        tags: {
          type: "array",
          items: { type: "string" }
        },
        rubric: { type: "string" },
        questions: {
          type: "array",
          items: {
            anyOf: [
              {
                type: "object",
                properties: {
                  type: {
                    type: "string",
                    enum: ["text"]
                  },
                  lang: { type: "string" },
                  id: { type: "string" },
                  value: { type: "string" },
                  comment: { type: "string" }
                }
              },
              {
                type: "object",
                properties: {
                  type: {
                    type: "string",
                    enum: ["kana"]
                  },
                  id: { type: "string" },
                  value: { type: "string" },
                  comment: { type: "string" }
                }
              },
              {
                type: "object",
                properties: {
                  type: {
                    type: "string",
                    enum: ["kanji"]
                  },
                  kanji: { type: "string" },
                  id: { type: "string" },
                  value: { type: "string" },
                  comment: { type: "string" }
                }
              },
              {
                type: "object",
                properties: {
                  type: {
                    type: "string",
                    enum: ["code"]
                  },
                  lang: { type: "string" },
                  id: { type: "string" },
                  value: { type: "string" },
                  comment: { type: "string" }
                }
              },
              {
                type: "object",
                properties: {
                  type: {
                    type: "string",
                    enum: ["math"]
                  },
                  id: { type: "string" },
                  value: { type: "string" },
                  comment: { type: "string" }
                }
              }
            ]
          }
        },
        comment: { type: "string" },
        navigationMode: {
          enum: ["random", "sequential"],
          type: "string"
        }
      }
    },
    ExerciseRevision: {
      type: "object",
      properties: {
        detailId: {
          format: "uuid",
          type: "string"
        },
        contentId: {
          format: "uuid",
          type: "string"
        }
      }
    },
    ExerciseRevisionDetail: {
      type: "object",
      properties: {
        title: { type: "string" },
        lang: { type: "string" },
        description: { type: "string" },
        tags: {
          type: "array",
          items: { type: "string" }
        },
        rubric: { type: "string" },
        questions: {
          type: "array",
          items: {
            anyOf: [
              {
                type: "object",
                properties: {
                  type: {
                    type: "string",
                    enum: ["text"]
                  },
                  lang: { type: "string" },
                  id: { type: "string" },
                  value: { type: "string" },
                  comment: { type: "string" }
                }
              },
              {
                type: "object",
                properties: {
                  type: {
                    type: "string",
                    enum: ["kana"]
                  },
                  id: { type: "string" },
                  value: { type: "string" },
                  comment: { type: "string" }
                }
              },
              {
                type: "object",
                properties: {
                  type: {
                    type: "string",
                    enum: ["kanji"]
                  },
                  kanji: { type: "string" },
                  id: { type: "string" },
                  value: { type: "string" },
                  comment: { type: "string" }
                }
              },
              {
                type: "object",
                properties: {
                  type: {
                    type: "string",
                    enum: ["code"]
                  },
                  lang: { type: "string" },
                  id: { type: "string" },
                  value: { type: "string" },
                  comment: { type: "string" }
                }
              },
              {
                type: "object",
                properties: {
                  type: {
                    type: "string",
                    enum: ["math"]
                  },
                  id: { type: "string" },
                  value: { type: "string" },
                  comment: { type: "string" }
                }
              }
            ]
          }
        },
        comment: { type: "string" },
        navigationMode: {
          enum: ["random", "sequential"],
          type: "string"
        },
        revisionId: {
          format: "uuid",
          type: "string"
        }
      }
    },
    ExerciseTag: {
      type: "object",
      properties: { name: { type: "string" } }
    },
    User: {
      type: "object",
      properties: {
        name: { type: "string" },
        permission: {
          enum: [
            "Admin",
            "Guest",
            "Owner",
            "Write"
          ],
          type: "string"
        },
        configId: {
          format: "uuid",
          type: "string"
        }
      }
    },
    UserAccount: {
      type: "object",
      properties: {
        userId: {
          format: "uuid",
          type: "string"
        },
        provider: {
          type: "string",
          enum: ["github"]
        },
        accountId: { type: "string" }
      }
    },
    UserConfig: {
      type: "object",
      properties: {
        theme: {
          enum: [
            "dark",
            "default",
            "light",
            "system"
          ],
          type: "string"
        },
        lang: {
          enum: ["default", "en", "ja", "system"],
          type: "string"
        }
      }
    },
    UserSession: {
      type: "object",
      properties: {
        userId: {
          format: "uuid",
          type: "string"
        },
        userAgent: { type: "string" }
      }
    }
  }
};
