/**
 * This file was automatically generated by typescript-json-schema
 */
import { Definition } from "typescript-json-schema";

export const SaveParamsMapSchema: Definition = {
  type: "object",
  properties: {
    Exercise: {
      type: "object",
      properties: {
        title: { type: "string" },
        authorId: { format: "uuid", type: "string" },
        summaryId: { format: "uuid", type: "string" },
        lang: { type: "string" },
        tags: {
          type: "array",
          items: { type: "object", properties: { id: { type: "number" }, name: { type: "string" } } }
        },
        description: { type: "string" },
        rubric: { type: "string" },
        comment: { type: "string" },
        questions: {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: { type: "number" },
              format: { enum: ["code", "math", "plain"], type: "string" },
              lang: { type: "string" },
              value: { type: "string" },
              comment: { type: "string" }
            }
          }
        },
        isPrivate: { type: "boolean" },
        isLocked: { type: "boolean" }
      }
    },
    ExerciseSummary: {
      type: "object",
      properties: {
        title: { type: "string" },
        authorId: { format: "uuid", type: "string" },
        lang: { type: "string" },
        tags: { type: "array", items: { type: "string" } },
        description: { type: "string" },
        exerciseId: { format: "uuid", type: "string" },
        submitCount: { type: "number" }
      }
    },
    ExerciseTag: { type: "object", properties: { name: { type: "string" } } },
    Submission: {
      type: "object",
      properties: {
        time: { type: "number" },
        exerciseId: { format: "uuid", type: "string" },
        userId: { format: "uuid", type: "string" },
        typeCount: { type: "number" },
        accuracy: { type: "number" }
      }
    },
    SubmissionSummary: {
      type: "object",
      properties: {
        exerciseId: { format: "uuid", type: "string" },
        submitCount: { type: "number" },
        userId: { format: "uuid", type: "string" },
        exerciseSummaryId: { format: "uuid", type: "string" },
        latest: {
          type: "object",
          properties: { typeCount: { type: "number" }, time: { type: "number" }, accuracy: { type: "number" } }
        },
        best: {
          type: "object",
          properties: { typeCount: { type: "number" }, time: { type: "number" }, accuracy: { type: "number" } }
        }
      }
    },
    User: {
      type: "object",
      properties: {
        name: { type: "string" },
        summaryId: { format: "uuid", type: "string" },
        permission: { enum: ["Admin", "Guest", "Owner", "Write"], type: "string" },
        accountId: { format: "uuid", type: "string" },
        configId: { format: "uuid", type: "string" }
      }
    },
    UserAccount: {
      type: "object",
      properties: {
        accountId: { type: "string" },
        provider: { type: "string", enum: ["github"] },
        email: { type: "string" }
      }
    },
    UserConfig: {
      type: "object",
      properties: {
        lang: { enum: ["default", "en", "ja", "system"], type: "string" },
        theme: { enum: ["dark", "default", "light", "system"], type: "string" }
      }
    },
    UserSession: {
      type: "object",
      properties: {
        browser: { type: "string" },
        userId: { format: "uuid", type: "string" },
        accessCount: { type: "number" },
        deviceType: { type: "string" },
        deviceName: { type: "string" },
        os: { type: "string" },
        isCurrent: { type: "boolean" }
      }
    },
    UserSummary: {
      type: "object",
      properties: {
        submitCount: { type: "number" },
        userId: { format: "uuid", type: "string" },
        typeCount: { type: "number" }
      }
    }
  }
};
