/**
 * This file was automatically generated by typescript-json-schema
 */
import { Definition } from "typescript-json-schema";

export const SearchParamsMapSchema: Definition = {
  type: "object",
  properties: {
    Content: {
      allOf: [
        {
          type: "object",
          properties: {
            summary: { type: "string" },
            title: { type: "string" },
            authorId: { type: "string" },
            latestId: { type: "string" },
            tagIds: {
              type: "array",
              items: { type: "string" }
            },
            lang: { type: "string" },
            isPrivate: { type: "boolean" }
          }
        },
        {
          type: "object",
          properties: { page: { type: "number" } }
        }
      ]
    },
    ContentRevision: {
      allOf: [
        {
          type: "object",
          properties: {
            summary: { type: "string" },
            title: { type: "string" },
            lang: { type: "string" },
            contentId: { type: "string" },
            tags: {
              type: "array",
              items: { type: "string" }
            },
            comment: { type: "string" },
            items: {
              type: "array",
              items: {
                anyOf: [
                  {
                    type: "object",
                    properties: {
                      type: {
                        type: "string",
                        enum: ["text"]
                      },
                      lang: { type: "string" },
                      id: { type: "string" },
                      value: { type: "string" },
                      comment: { type: "string" }
                    }
                  },
                  {
                    type: "object",
                    properties: {
                      type: {
                        type: "string",
                        enum: ["kana"]
                      },
                      id: { type: "string" },
                      value: { type: "string" },
                      comment: { type: "string" }
                    }
                  },
                  {
                    type: "object",
                    properties: {
                      type: {
                        type: "string",
                        enum: ["kanji"]
                      },
                      kanji: { type: "string" },
                      id: { type: "string" },
                      value: { type: "string" },
                      comment: { type: "string" }
                    }
                  },
                  {
                    type: "object",
                    properties: {
                      type: {
                        type: "string",
                        enum: ["code"]
                      },
                      lang: { type: "string" },
                      id: { type: "string" },
                      value: { type: "string" },
                      comment: { type: "string" }
                    }
                  },
                  {
                    type: "object",
                    properties: {
                      type: {
                        type: "string",
                        enum: ["math"]
                      },
                      id: { type: "string" },
                      value: { type: "string" },
                      comment: { type: "string" }
                    }
                  }
                ]
              }
            },
            isLinear: { type: "boolean" }
          }
        },
        {
          type: "object",
          properties: { page: { type: "number" } }
        }
      ]
    },
    ContentTag: {
      allOf: [
        {
          type: "object",
          properties: { name: { type: "string" } }
        },
        {
          type: "object",
          properties: { page: { type: "number" } }
        }
      ]
    },
    User: {
      allOf: [
        {
          type: "object",
          properties: {
            name: { type: "string" },
            permission: {
              enum: [
                "Admin",
                "Ghost",
                "Guest",
                "Owner",
                "Write"
              ],
              type: "string"
            }
          }
        },
        {
          type: "object",
          properties: { page: { type: "number" } }
        }
      ]
    },
    UserAccount: {
      allOf: [
        {
          type: "object",
          properties: {
            userId: { type: "string" },
            provider: {
              type: "string",
              enum: ["github"]
            },
            accountId: { type: "string" }
          }
        },
        {
          type: "object",
          properties: { page: { type: "number" } }
        }
      ]
    },
    UserConfig: {
      allOf: [
        {
          type: "object",
          properties: {
            name: { type: "string" },
            userId: { type: "string" },
            settings: {
              type: "object",
              properties: {
                theme: {
                  enum: ["dark", "light"],
                  type: "string"
                },
                lang: {
                  enum: ["en", "ja"],
                  type: "string"
                }
              }
            }
          }
        },
        {
          type: "object",
          properties: { page: { type: "number" } }
        }
      ]
    },
    UserSession: {
      allOf: [
        {
          type: "object",
          properties: {
            userId: { type: "string" },
            userAgent: { type: "string" }
          }
        },
        {
          type: "object",
          properties: { page: { type: "number" } }
        }
      ]
    }
  }
};
