/**
 * This file was automatically generated by typescript-json-schema
 */
import { Definition } from "typescript-json-schema";

export const SaveParamsMapSchema: Definition = {
  type: "object",
  properties: {
    Exercise: {
      type: "object",
      properties: {
        authorId: { format: "uuid", type: "string" },
        summaryId: { format: "uuid", type: "string" },
        isPrivate: { type: "boolean" },
        isLocked: { type: "boolean" },
        lang: { type: "string" },
        title: { type: "string" },
        tags: { type: "array", items: { type: "string" } },
        description: { type: "string" },
        questions: {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: { type: "number" },
              lang: { type: "string" },
              format: { type: "string" },
              value: { type: "string" },
              comment: { type: "string" }
            }
          }
        },
        isRandom: { type: "boolean" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    ExerciseDiary: {
      type: "object",
      properties: {
        exerciseId: { format: "uuid", type: "string" },
        date: { type: "string" },
        submittedCount: { type: "number" },
        typedCount: { type: "number" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    ExerciseDraft: {
      type: "object",
      properties: {
        exerciseId: { format: "uuid", type: "string" },
        isMerged: { type: "boolean" },
        lang: { type: "string" },
        title: { type: "string" },
        tags: { type: "array", items: { type: "string" } },
        description: { type: "string" },
        questions: {
          type: "array",
          items: {
            type: "object",
            properties: {
              id: { type: "number" },
              lang: { type: "string" },
              format: { type: "string" },
              value: { type: "string" },
              comment: { type: "string" }
            }
          }
        },
        isRandom: { type: "boolean" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    ExerciseReport: {
      type: "object",
      properties: {
        targetId: { format: "uuid", type: "string" },
        reporterId: { format: "uuid", type: "string" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    ExerciseSummary: {
      type: "object",
      properties: {
        authorId: { format: "uuid", type: "string" },
        exerciseId: { format: "uuid", type: "string" },
        draftId: { format: "uuid", type: "string" },
        lang: { type: "string" },
        title: { type: "string" },
        tags: { type: "string" },
        description: { type: "string" },
        upvoteCount: { type: "number" },
        submitCount: { type: "number" },
        isPrivate: { type: "boolean" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    ExerciseTag: {
      type: "object",
      properties: {
        name: { type: "string" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    ExerciseVote: {
      type: "object",
      properties: {
        targetId: { format: "uuid", type: "string" },
        voterId: { format: "uuid", type: "string" },
        isUp: { type: "boolean" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    Playlist: {
      type: "object",
      properties: {
        authorId: { format: "uuid", type: "string" },
        summaryId: { format: "uuid", type: "string" },
        title: { type: "string" },
        tags: { type: "array", items: { type: "string" } },
        description: { type: "string" },
        orderBy: {
          enum: [
            "date_added_asc",
            "date_added_desc",
            "date_published_asc",
            "date_published_desc",
            "manual_bottom",
            "manual_top",
            "submit_count_desc"
          ],
          type: "string"
        },
        isPrivate: { type: "boolean" },
        isLocked: { type: "boolean" },
        exerciseId: { format: "uuid", type: "string" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    PlaylistBookmark: {
      type: "object",
      properties: {
        userId: { format: "uuid", type: "string" },
        playlistId: { format: "uuid", type: "string" },
        memo: { type: "string" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    PlaylistItem: {
      type: "object",
      properties: {
        playlistId: { format: "uuid", type: "string" },
        exerciseId: { format: "uuid", type: "string" },
        exerciseSummaryId: { format: "uuid", type: "string" },
        nextId: { format: "uuid", type: "string" },
        memo: { type: "string" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    PlaylistReport: {
      type: "object",
      properties: {
        targetId: { format: "uuid", type: "string" },
        reporterId: { format: "uuid", type: "string" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    PlaylistSummary: {
      type: "object",
      properties: {
        authorId: { format: "uuid", type: "string" },
        playlistId: { format: "uuid", type: "string" },
        title: { type: "string" },
        tags: { type: "string" },
        description: { type: "string" },
        itemCount: { type: "number" },
        isPrivate: { type: "boolean" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    PlaylistTag: {
      type: "object",
      properties: {
        name: { type: "string" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    Submission: {
      type: "object",
      properties: {
        submitterId: { format: "uuid", type: "string" },
        exerciseId: { format: "uuid", type: "string" },
        typeCount: { minimum: 1, type: "number" },
        time: { minimum: 1, type: "number" },
        accuracy: { minimum: 0, maximum: 100, type: "number" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    SubmissionSummary: {
      type: "object",
      properties: {
        submitterId: { format: "uuid", type: "string" },
        exerciseId: { format: "uuid", type: "string" },
        exerciseSummaryId: { format: "uuid", type: "string" },
        latest: {
          type: "object",
          properties: { typeCount: { type: "number" }, time: { type: "number" }, accuracy: { type: "number" } }
        },
        submitCount: { type: "number" },
        typeCount: { type: "number" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    User: {
      type: "object",
      properties: {
        name: { type: "string" },
        permission: { enum: ["Admin", "Guest", "Owner", "Read", "Write"], type: "string" },
        accountId: { format: "uuid", type: "string" },
        configId: { format: "uuid", type: "string" },
        summaryId: { format: "uuid", type: "string" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    UserAccount: {
      type: "object",
      properties: {
        provider: { type: "string", enum: ["github"] },
        accountId: { type: "string" },
        email: { type: "string" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    UserConfig: {
      type: "object",
      properties: {
        lang: { enum: ["default", "en", "ja", "system"], type: "string" },
        theme: { enum: ["dark", "default", "light", "system"], type: "string" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    UserDiary: {
      type: "object",
      properties: {
        userId: { format: "uuid", type: "string" },
        date: { type: "string" },
        submitCount: { type: "number" },
        typeCount: { type: "number" },
        submittedCount: { type: "number" },
        typedCount: { type: "number" },
        createCount: { type: "number" },
        editCount: { type: "number" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    UserReport: {
      type: "object",
      properties: {
        targetId: { format: "uuid", type: "string" },
        reporterId: { format: "uuid", type: "string" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    UserSession: {
      type: "object",
      properties: {
        userId: { format: "uuid", type: "string" },
        accessCount: { type: "number" },
        deviceType: { type: "string" },
        deviceName: { type: "string" },
        os: { type: "string" },
        browser: { type: "string" },
        isCurrent: { type: "boolean" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    },
    UserSummary: {
      type: "object",
      properties: {
        userId: { format: "uuid", type: "string" },
        submitCount: { type: "number" },
        typeCount: { type: "number" },
        id: { format: "uuid", type: "string" },
        createdAt: { type: "number" },
        updatedAt: { type: "number" },
        fetchedAt: { type: "number" }
      }
    }
  }
};
