/**
 * This file was automatically generated by typescript-json-schema
 */
import { Definition } from "typescript-json-schema";

export const SearchParamsMapSchema: Definition = {
  type: "object",
  properties: {
    Exercise: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            authorId: { format: "uuid", type: "string" },
            summaryId: { format: "uuid", type: "string" },
            lang: { type: "string" },
            title: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
            description: { type: "string" },
            questions: {
              type: "array",
              items: {
                type: "object",
                properties: {
                  id: { type: "number" },
                  lang: { type: "string" },
                  format: { type: "string" },
                  value: { type: "string" },
                  comment: { type: "string" }
                }
              }
            },
            isPrivate: { type: "boolean" },
            isLocked: { type: "boolean" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    ExerciseDiary: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            exerciseId: { format: "uuid", type: "string" },
            date: { type: "string" },
            submittedCount: { type: "number" },
            typedCount: { type: "number" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    ExerciseReport: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            targetId: { format: "uuid", type: "string" },
            reporterId: { format: "uuid", type: "string" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    ExerciseSummary: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            authorId: { format: "uuid", type: "string" },
            exerciseId: { format: "uuid", type: "string" },
            lang: { type: "string" },
            title: { type: "string" },
            tags: { type: "string" },
            description: { type: "string" },
            upvoteCount: { type: "number" },
            submitCount: { type: "number" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    ExerciseTag: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            name: { type: "string" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    ExerciseVote: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            targetId: { format: "uuid", type: "string" },
            voterId: { format: "uuid", type: "string" },
            isUp: { type: "boolean" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    Playlist: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            authorId: { format: "uuid", type: "string" },
            title: { type: "string" },
            tags: { type: "array", items: { type: "string" } },
            description: { type: "string" },
            isPrivate: { type: "boolean" },
            isLocked: { type: "boolean" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    PlaylistBookmark: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            userId: { format: "uuid", type: "string" },
            playlistId: { format: "uuid", type: "string" },
            memo: { type: "string" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    PlaylistItem: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            playlistId: { format: "uuid", type: "string" },
            exerciseId: { format: "uuid", type: "string" },
            exerciseSummaryId: { format: "uuid", type: "string" },
            nextId: { format: "uuid", type: "string" },
            memo: { type: "string" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    PlaylistReport: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            targetId: { format: "uuid", type: "string" },
            reporterId: { format: "uuid", type: "string" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    PlaylistSummary: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            authorId: { format: "uuid", type: "string" },
            playlistId: { format: "uuid", type: "string" },
            title: { type: "string" },
            tags: { type: "string" },
            description: { type: "string" },
            itemCount: { type: "number" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    PlaylistTag: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            name: { type: "string" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    Submission: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            submitterId: { format: "uuid", type: "string" },
            exerciseId: { format: "uuid", type: "string" },
            typeCount: { minimum: 1, type: "number" },
            time: { minimum: 1, type: "number" },
            accuracy: { minimum: 0, maximum: 100, type: "number" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    SubmissionSummary: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            submitterId: { format: "uuid", type: "string" },
            exerciseId: { format: "uuid", type: "string" },
            exerciseSummaryId: { format: "uuid", type: "string" },
            latest: {
              type: "object",
              properties: { typeCount: { type: "number" }, time: { type: "number" }, accuracy: { type: "number" } }
            },
            submitCount: { type: "number" },
            typeCount: { type: "number" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    User: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            name: { type: "string" },
            permission: { enum: ["Admin", "Guest", "Owner", "Read", "Write"], type: "string" },
            accountId: { format: "uuid", type: "string" },
            configId: { format: "uuid", type: "string" },
            summaryId: { format: "uuid", type: "string" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    UserAccount: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            provider: { type: "string", enum: ["github"] },
            accountId: { type: "string" },
            email: { type: "string" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    UserConfig: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            lang: { enum: ["default", "en", "ja", "system"], type: "string" },
            theme: { enum: ["dark", "default", "light", "system"], type: "string" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    UserDiary: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            userId: { format: "uuid", type: "string" },
            date: { type: "string" },
            submitCount: { type: "number" },
            typeCount: { type: "number" },
            submittedCount: { type: "number" },
            typedCount: { type: "number" },
            createCount: { type: "number" },
            editCount: { type: "number" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    UserReport: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            targetId: { format: "uuid", type: "string" },
            reporterId: { format: "uuid", type: "string" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    UserSession: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            userId: { format: "uuid", type: "string" },
            accessCount: { type: "number" },
            deviceType: { type: "string" },
            deviceName: { type: "string" },
            os: { type: "string" },
            browser: { type: "string" },
            isCurrent: { type: "boolean" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    },
    UserSummary: {
      allOf: [
        { type: "object", properties: { limit: { type: "number" }, offset: { type: "number" } } },
        {
          type: "object",
          properties: {
            userId: { format: "uuid", type: "string" },
            submitCount: { type: "number" },
            typeCount: { type: "number" },
            id: { format: "uuid", type: "string" },
            createdAt: { type: "number" },
            updatedAt: { type: "number" },
            fetchedAt: { type: "number" }
          }
        }
      ]
    }
  }
};
