import { EntityType } from "./entities";

export const endpoints: { [P in EntityType]: string } = {
  Contest: "contests",
  ContestEntry: "contest-entries",
  Exercise: "exercises",
  ExerciseDiary: "exercise-diaries",
  ExerciseDraft: "exercise-drafts",
  ExerciseSummary: "exercise-summaries",
  ExerciseVote: "exercise-votes",
  Group: "groups",
  GroupApplication: "group-applications",
  GroupExercise: "group-exercises",
  GroupInvitation: "group-invitations",
  GroupMember: "group-members",
  GroupSecret: "group-secrets",
  GroupSummary: "group-summaries",
  Objection: "objections",
  Playlist: "playlists",
  PlaylistBookmark: "playlist-bookmarks",
  PlaylistItem: "playlist-items",
  PlaylistSummary: "playlist-summaries",
  Report: "reports",
  Revision: "revisions",
  RevisionSummary: "revision-summaries",
  Submission: "submissions",
  SubmissionSummary: "submission-summaries",
  Suggestion: "suggestions",
  SuggestionSummary: "suggestion-summaries",
  Synonym: "synonyms",
  Tag: "tags",
  TagFollow: "tag-follows",
  TagSummary: "tag-summaries",
  User: "users",
  UserAccount: "user-accounts",
  UserConfig: "user-configs",
  UserDiary: "user-diaries",
  UserFollow: "user-follows",
  UserMessage: "user-messages",
  UserSession: "user-sessions",
  UserSummary: "user-summaries"
};
