name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@master
      - name: Init Database
        run: |
          mysql -h127.0.0.1 -uroot -proot --execute='CREATE DATABASE IF NOT EXISTS test;'
      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, and test
        run: |
          yarn install
          yarn build
          yarn lint
          yarn test:ts
          yarn test:jest:cov
        env:
          NODE_ENV: test
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: root
          DATABASE_NAME: test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
