name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Init Database
        run: |
          mysql --host=127.0.0.1 --user=root --password=root --execute 'CREATE DATABASE IF NOT EXISTS test;'
      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          yarn install
          yarn build
          yarn lint
          yarn test:ci
        env:
          NODE_ENV: test
          DATABASE_USERNAME: root
          DATABASE_PASSWORD: root
          DATABASE_NAME: test
